### PR TITLE
adds grid_type argument to datagrid

### PR DESCRIPTION
**Pull request by LamAdr**
The book uses the `grid_type`  argument. Do you want to support it?
Otherwise I can just use `datagridcf` directly.

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Yes, can you also remove the `grid_type` everywhere you see it in the R code and use `datagridcf()` instead? thanks!

**Comment by vincentarelbundock** [comment]
Meaning, I don't think we need to make this change in Python. I would rather soft deprecate this in R.

**Comment by LamAdr** [comment]
Sure. You want me to remove the `grid_type` references in the book only or in the R code too?

**Comment by vincentarelbundock** [comment]
Just the book.

**Pull request closed without merging**
