### PR TITLE
issue114_plot_slopes fix

### PR DESCRIPTION
**Pull request by artiom-matvei**
Fixes:
* makes variables argument mandatory for plot_slopes
* makes minmax, threenum, fivenum appear (apparently it degraded from last PR so I had to fix it again)

### CODE REVIEW

**Comment by artiom-matvei** [comment]
# R Version
plot_comparisons and plot_slopes require the `variables` argument in R

# Python Version
 plot_comparisons and plot_slopes do NOT require the `variables` argument in python

Should it be made required in Python?  @vincentarelbundock

**Comment by vincentarelbundock** [comment]
Yes, this absolutely should be a required argument

**Comment by vincentarelbundock** [comment]
I was going to fix the lint issue myself, but you have not given upstream maintainers commit rights to your PRs.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by artiom-matvei** [comment]
I just granted you commit rights to the PR. Let me know if it works.

**Comment by vincentarelbundock** [comment]
@artiom-matvei yep, thanks. I was able to lint and merge main. 

Tests are still failing on images, so I assume this is still WIP.

**Comment by vincentarelbundock** [comment]
This is fantastic, thanks so much!

**Pull request merged**
