### PR TITLE
predictions dmatrix and remove padding

### LINKED ISSUE #83: Missing values leading to ValueError: "Something went wrong" in predictions()
Hey @vincentarelbundock,

It seems fitting a statsmodel or predicting from a statsmodel using incomplete data leads to a `"ValueError: Something went wrong"` in `marginaleffects.predictions()` at this [line](https://github.com/vincentarelbundock/pymarginaleffects/blob/d0f7dad2960161afcd04d3a7927b783020f3df44/marginaleffects/predictions.py#L168). 

I created some examples to demonstrate:

1. Example 1: model fitted on incomplete data, predicting on incomplete data
2. Example 2: model fitted on complete data, predicting on incomplete data
3. Example 3: model fitted on incomplete data, predicting on complete data

```python
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from marginaleffects import predictions

diamonds = pd.read_csv("https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/ggplot2/diamonds.csv")

# Example 1: model fitted on incomplete data, predicting on incomplete data

# Introduce missing values
diamonds['cut_ideal_null'] = diamonds['cut'].where(diamonds['cut'] != 'Ideal', None)

model = smf.ols("price ~ cut_ideal_null", data = diamonds).fit()

newdata = diamonds.iloc[0:20,:].copy()

# Works
model.predict(newdata)

# Fails: ValueError: Something went wrong
predictions(model, newdata=newdata)


# Example 2: model fitted on complete data, predicting on incomplete data

model = smf.ols("price ~ cut", data = diamonds).fit()

newdata = diamonds.iloc[0:20,:].copy()

# Introduce missing values
newdata['cut'] = newdata['cut'].where(newdata['cut'] != 'Ideal', None)

# Works
model.predict(newdata)

# Fails: ValueError: Something went wrong
predictions(model, newdata=newdata)


# Example 3: model fitted on incomplete data, predicting on complete data

diamonds['cut_ideal_null'] = diamonds['cut'].where(diamonds['cut'] != 'Ideal', None)

model = smf.ols("price ~ cut_ideal_null", data = diamonds).fit()

newdata = diamonds.iloc[0:20,:].copy()
newdata['cut_ideal_null'] = newdata['cut'].where(newdata['cut'] != 'Ideal', 'Premium')

# Works
model.predict(newdata)

# Fails: ValueError: Something went wrong
predictions(model, newdata=newdata)
```

### PR DESCRIPTION
**Pull request by LamAdr**
This fixes #83 and #95 with @RoelVerbelen's suggestions.

- all padding code is boldly removed. Given that I barely understands what it does that might be naive.
- we get `exog` from `dmatrix` using `design_info`, not formula.
- the `NA_action="raise"` is used to flag missing values. I found Patsy's error message pretty informative so I did not catch it.

Please tell me if I should change anything

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
I think the errors are because of differences in plots. If you have time, could you see what's up with that? Are the plots really different, or are they minor pixel differences?

(that should probably be a separate PR that we merge in here)

**Comment by LamAdr** [comment]
Yeah looks like minor pixel differences. Should i regenerate the images?

**Comment by vincentarelbundock** [comment]
Yep, if there's really no substantive difference, then feel free to re-generate. Thanks!

**Comment by vincentarelbundock** [comment]
Thanks!

**Pull request merged**
